### ISSUE TITLE
Cannot read property 'appendChild' of undefined

### ISSUE THREAD

**Issue by mishanthrop** [binarybaba/prophetjs#3]
Including script and css:
```
<script src="/operator/prophet-min.js"></script>
<link rel="stylesheet" href="/operator/prophet.min.css" type="text/css" />
```
Trying to show simple toast:
```
<script>
    var toast = new Message('Harambe for president!');
    console.log(toast);
    toast.show();
</script>
```
Result:
![image](https://user-images.githubusercontent.com/5341208/42384992-415c088c-8144-11e8-970d-5d5572b96611.png)

![image](https://user-images.githubusercontent.com/5341208/42385065-6fb1e47c-8144-11e8-85d4-1ebcc0da87a1.png)

**Comment by binarybaba** [comment]
Hmm.. I think you're running the initing the toast before loading the script and that's why its unable to find the ul.
I created a jsfiddle [here](http://jsfiddle.net/hpz9rntu/3/) for you to see.

**Comment by mishanthrop** [comment]
@binarybaba thanks for response, I will try later. 
I tried your library on another machine, scripts are included before creating toasts (to the best of my memory).

**Comment by binarybaba** [comment]
that shouldn't happen. Anyway, lemme know what happens when you try again. Not closing this issue for now.

**Comment by mishanthrop** [comment]
Now it works, thanks for demo.
I just wrapped the code in a wrapper (`$ (document) .ready`).

Also earlier I included the library before writing, but the library requires creating of `ul` at first. I think, it is useless to create this `ul` manually, and this `ul` is useless at all.

**Comment by binarybaba** [comment]
hmm.. you're right. We shouldn't make this ul manually. the lib should take care of that. Buit the ul isn't useless because it acts as a hook for more than one toasts.
I'll close this issue for now.
To the readers: I think a good first PR will be removing the manual addition of ul and have the library do it
